select * from hospital;
-- Total patients --
select count(*) from hospital ;
-- Total doctors
select count(distinct doctorname) as total_doctors from hospital; 
-- total departments
select count(distinct department) as total_dept from hospital; 
-- Gender Distribution 
select gender, count(*) as total_patient from hospital group by gender;
-- Most common disease 
select disease, count(*) as total_patients from hospital group by disease order by total_patients desc ;
 -- department wise patient count 
select department , count(Patientid) as total_patients from hospital group by department order by total_patients desc;
-- Total Revenue
select sum(totalbillamount)as total_revenue from hospital;
-- Average bill Amount
select avg(totalbillamount) as avg_amount from hospital;  
-- total revenue by department 
select department, sum(totalbillamount)as Total_revenue from hospital group by department;
--  Total revenue by payment mode
select paymentmode, sum(totalbillamount) as total_revenue from hospital group by paymentmode;

                      -- DATA ANALYSIS --
-- Monthly Patient Trend --
select monthname(admissiondate) as month,
count(*) as total_patients
from hospital
group by month(admissiondate), monthname(admissiondate)
order by month(Admissiondate);
-- monthly revenue
select monthname(admissiondate) as month,
sum(totalbillamount) as total_revenue
from hospital
group by month(admissiondate), monthname(admissiondate)
order by month(admissiondate); 
-- year-wise Revenue
select
year(admissiondate) as year,
sum(totalbillamount) as revenue
from hospital
group by year(admissiondate); 
              
              -- hospital performance 
alter table hospital add column hospitalstays int;
set sql_safe_updates = 0;
update hospital 
set hospitalstays = datediff(dischargedate, admissiondate);
set sql_safe_updates = 1;              
-- Average hospital stay
select round(avg(hospitalstays),0) as avg_hospital_stay
from hospital;     
-- average hospital stay by disease -- 
select disease, round(avg(hospitalstays), 0) as avg_hospital_stay
from hospital
group by disease; 
-- longest hospital stay
select patientname, disease, hospitalstays
from hospital
order by hospitalstays desc limit 1;
    -- hospital analysis --
-- top 10 doctors
select doctorname, count(*) as patient_treated
from hospital
group by doctorname
order by patient_treated desc
limit 10;  

-- Revenue by doctors
select doctorname, round(sum(totalbillamount),0) as revenue
from hospital
group by doctorname
order by revenue desc;
-- average consultation fee by doctors
select doctorname, avg(consultationfee) from hospital group by doctorname ;                                 
                                -- Disease Analysis
-- disease by gender
select gender, disease, count(*) as patients from hospital group by disease,gender; 
 -- disease revenue
select disease, round(sum(totalbillamount)) as revenue
from hospital
group by disease; 
-- financial analysis
-- total pending amount
select round(sum(pendingamount)) as total_revenue
from hospital;
-- highest pending amount
select patientname, disease, pendingamount from hospital order by pendingamount desc limit 1;   
-- revenue by insurance provider
select insuranceprovider, sum(totalbillamount) from hospital group by insuranceprovider; 
-- total paid revenue by department
select department, round(sum(amountpaid)) from hospital group by department; 
-- total revenue generated by doctors
select doctorname, round(sum(totalbillamount)) from hospital group by doctorname;
-- state Analysis--
-- state wise patient count
select state, count(*) from hospital group by state;  
-- state wise revenue
select state, round(sum(totalbillamount)) as revenue from hospital group by state order by revenue desc;                        
-- total pending amount by state
select state, round(sum(totalbillamount)) as revenue from hospital group by state order by revenue desc;

-- rank doctors by patients trend
select doctorname, count(*) as patients,
dense_rank() over(order by count(*) desc) as doctor_rank
from hospital group by doctorname;
-- patients above average bill
select patientname, totalbillamount from hospital where totalbillamount > (
select avg(totalbillamount) from hospital 
) ; 
-- revenue contribution by department
select department, 
sum(totalbillamount) as revenue,
round(sum(totalbillamount)/
(select sum(totalbillamount) from hospital)*100,2
) as revenue_percentage
from hospital
group by department;
--  top 5 disease admitted patients
select disease , count(*) as patient_count from hospital group by disease order by patient_count desc limit 5;








     